.NET 6 Core API implementation and example
SpecFlowOSS/SpecFlow-Examples pull request #77
Opened 2021-09-21 15:38 UTC by JordanWestern

2021-09-22 11:44 UTC, alimogithub approved these changes

2021-09-23 13:58 UTC, JordanWestern commented
@SabotageAndi ready for review

2021-09-27 11:20 UTC, SabotageAndi requested changes
Could you rename one of the two Calculator Classes? It confused me and first I thought, we call the class directly and not via REST.

The rest looks very good. Short example which shows the parts we want to show.

2021-09-27 12:08 UTC, JordanWestern commented
> Could you rename one of the two Calculator Classes? It confused me and first I thought, we call the class directly and not via REST.
> 
> The rest looks very good. Short example which shows the parts we want to show.

Updated @SabotageAndi

2021-09-28 08:17 UTC, merged